'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const projectRoot = path.resolve(__dirname, '../../..');
const doctor = path.join(projectRoot, '.github/agent-qa/doctor.cjs');
const SECRET = 'DOCTOR_SECRET_CANARY_4f2095';

function executable(target, body) {
  fs.writeFileSync(target, `#!/usr/bin/env bash\nset -euo pipefail\n${body}\n`, { mode: 0o700 });
}

function fixture(t) {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-qa-doctor-'));
  t.after(() => {
    fs.rmSync(temp, { recursive: true, force: true });
    assert.equal(fs.existsSync(temp), false);
  });
  const qaRoot = path.join(temp, 'qa-root');
  const runner = path.join(qaRoot, 'runner');
  const toolchain = path.join(qaRoot, 'toolchain');
  for (const dir of [qaRoot, runner, toolchain, path.join(qaRoot, 'runs')]) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.chmodSync(dir, 0o700);
  }
  executable(path.join(runner, 'run.sh'), 'exit 0');
  fs.writeFileSync(path.join(runner, '.runner-version'), '2.337.0\n');
  fs.writeFileSync(path.join(runner, '.runner'),
    '{"agentName":"gods-eye-agent-qa","gitHubUrl":"https://github.com/jayn2u/gods-eye"}');
  fs.writeFileSync(path.join(qaRoot, 'auth.lock'), '', { mode: 0o600 });

  const copilot = path.join(temp, 'copilot');
  // Mirrors the real CLI: the version carries a trailing period and an update notice follows it.
  executable(copilot, `
if [[ "\${1:-}" == '--version' ]]; then printf 'GitHub Copilot CLI 1.0.83.\nRun '\\''copilot update'\\'' to check for updates.\n'; exit; fi
exit 1`);
  const uv = path.join(temp, 'uv');
  executable(uv, "echo 'uv 0.12.6'");
  const mcp = path.join(temp, 'playwright-mcp');
  executable(mcp, "echo 'Version 0.0.80'");
  const pnpm = path.join(temp, 'pnpm');
  executable(pnpm, "echo '10.15.0'");
  const browser = path.join(temp, 'browser-probe');
  executable(browser, 'exit 0');
  const gh = path.join(temp, 'gh');
  executable(gh, `
if [[ "$1" == 'repo' ]]; then echo '{"nameWithOwner":"jayn2u/gods-eye","isPrivate":true}'; else echo '{"runners":[{"name":"gods-eye-agent-qa","labels":[{"name":"gods-eye-agent-qa"}]}]}'; fi`);
  const systemctl = path.join(temp, 'systemctl');
  executable(systemctl, "echo active");
  const loginctl = path.join(temp, 'loginctl');
  executable(loginctl, "echo yes");
  const flock = path.join(temp, 'flock');
  executable(flock, 'exit 0');

  const env = {
    ...process.env,
    QA_ROOT: qaRoot,
    QA_DEVELOPER_CHECKOUT: projectRoot,
    QA_COPILOT_BIN: copilot,
    QA_UV_BIN: uv,
    QA_PLAYWRIGHT_MCP_BIN: mcp,
    QA_PNPM_BIN: pnpm,
    QA_BROWSER_PROBE_BIN: browser,
    QA_GH_BIN: gh,
    QA_SYSTEMCTL_BIN: systemctl,
    QA_LOGINCTL_BIN: loginctl,
    QA_FLOCK_BIN: flock,
    QA_COPILOT_TOKEN: SECRET,
    GITHUB_ACTIONS: 'true',
  };
  delete env.OPENAI_API_KEY;
  delete env.AZURE_OPENAI_API_KEY;
  delete env.CODEX_API_KEY;
  delete env.ANTHROPIC_API_KEY;
  return { temp, qaRoot, browser, flock, env };
}

function run(env, extraArgs = []) {
  const result = spawnSync(process.execPath, [doctor, '--json', ...extraArgs], { env, encoding: 'utf8' });
  assert.doesNotThrow(() => JSON.parse(result.stdout), `stdout was not JSON: ${result.stdout}`);
  return { ...result, report: JSON.parse(result.stdout) };
}

function check(report, name) {
  return report.checks.find((item) => item.name === name);
}

test('reports ready from a workflow-supplied Copilot token and non-secret metadata', (t) => {
  const f = fixture(t);
  const result = run(f.env);
  assert.equal(result.status, 0);
  assert.equal(result.report.ok, true);
  assert.ok(result.report.checks.every((item) => item.ok));
  assert.equal(check(result.report, 'subscription_auth').token_source, 'QA_COPILOT_TOKEN');
  assert.doesNotMatch(`${result.stdout}${result.stderr}`, new RegExp(SECRET));
  assert.doesNotMatch(result.stdout, /access_token|refresh_token|id_token/);
});

test('recognizes a BOM-prefixed runner configuration generated by the real runner', (t) => {
  const f = fixture(t);
  fs.writeFileSync(path.join(f.qaRoot, 'runner/.runner'), Buffer.concat([
    Buffer.from([0xef, 0xbb, 0xbf]),
    Buffer.from('{"agentName":"gods-eye-agent-qa","gitHubUrl":"https://github.com/jayn2u/gods-eye"}'),
  ]));
  const result = run(f.env);
  assert.equal(result.status, 0);
  assert.equal(check(result.report, 'runner_registration').local_configured, true);
});

test('a missing agent token inside a workflow is not accepted', (t) => {
  const f = fixture(t);
  const env = { ...f.env };
  delete env.QA_COPILOT_TOKEN;
  const result = run(env);
  assert.notEqual(result.status, 0);
  const auth = check(result.report, 'subscription_auth');
  assert.equal(auth.token_present, false);
  assert.equal(auth.token_source, 'missing');
  assert.equal(auth.required, true);
  assert.equal(auth.ok, false);
});

test('a token absent outside a workflow is reported without failing a read-only check', (t) => {
  const f = fixture(t);
  const env = { ...f.env };
  delete env.QA_COPILOT_TOKEN;
  delete env.GITHUB_ACTIONS;
  const result = run(env);
  assert.equal(result.status, 0);
  const auth = check(result.report, 'subscription_auth');
  assert.equal(auth.token_present, false);
  assert.equal(auth.token_source, 'workflow-secret');
  assert.equal(auth.required, false);
  assert.equal(auth.ok, true);
});

test('a competing provider credential fails readiness and never reaches the report', async (t) => {
  for (const name of ['OPENAI_API_KEY', 'CODEX_API_KEY', 'ANTHROPIC_API_KEY', 'AZURE_OPENAI_API_KEY']) {
    await t.test(name, (subtest) => {
      const f = fixture(subtest);
      const result = run({ ...f.env, [name]: SECRET });
      assert.notEqual(result.status, 0);
      const auth = check(result.report, 'subscription_auth');
      assert.equal(auth.foreign_provider_environment, true);
      assert.equal(auth.ok, false);
      assert.doesNotMatch(`${result.stdout}${result.stderr}`, new RegExp(SECRET));
    });
  }
});

test('the agent token never appears in the preflight report', (t) => {
  const f = fixture(t);
  const result = run(f.env);
  assert.doesNotMatch(`${result.stdout}${result.stderr}`, new RegExp(SECRET));
});

test('inside a job the runner workspace under QA_ROOT is not treated as a developer checkout', (t) => {
  const f = fixture(t);
  const workspace = path.join(f.qaRoot, 'runs', 'gods-eye', 'gods-eye');
  fs.mkdirSync(workspace, { recursive: true });
  const env = { ...f.env };
  delete env.QA_DEVELOPER_CHECKOUT;
  const result = spawnSync(process.execPath, [doctor, '--json'], { env, encoding: 'utf8', cwd: workspace });
  const report = JSON.parse(result.stdout);
  const paths = report.checks.find((item) => item.name === 'paths');
  assert.equal(paths.ok, true);
  assert.equal(paths.developer_checkout, 'not-applicable');
  assert.equal(result.status, 0, result.stderr);
});

test('a declared developer checkout containing QA_ROOT still fails', (t) => {
  const f = fixture(t);
  const result = run({ ...f.env, QA_DEVELOPER_CHECKOUT: path.dirname(f.qaRoot) });
  assert.notEqual(result.status, 0);
  const paths = result.report.checks.find((item) => item.name === 'paths');
  assert.equal(paths.ok, false);
  assert.equal(paths.developer_checkout, 'declared');
});

test('only harness-controlled tools are version-pinned; the build toolchain needs presence', async (t) => {
  await t.test('a drifting pnpm is accepted and recorded', (subtest) => {
    const f = fixture(subtest);
    executable(f.env.QA_PNPM_BIN, "echo '11.24.0'");
    const result = run(f.env);
    assert.equal(result.status, 0, result.stderr);
    const versions = check(result.report, 'tool_versions');
    assert.equal(versions.ok, true);
    assert.equal(versions.pnpm, '11.24.0');
    assert.equal(versions.pinned, 'node,copilot,playwright_mcp');
  });
  await t.test('an absent pnpm is still rejected', (subtest) => {
    const f = fixture(subtest);
    executable(f.env.QA_PNPM_BIN, 'exit 1');
    const result = run(f.env);
    assert.notEqual(result.status, 0);
    assert.equal(check(result.report, 'tool_versions').ok, false);
  });
  await t.test('a drifting pinned agent is rejected', (subtest) => {
    const f = fixture(subtest);
    executable(f.env.QA_COPILOT_BIN, `if [[ "\${1:-}" == '--version' ]]; then echo 'GitHub Copilot CLI 1.0.84.'; exit; fi; exit 1`);
    const result = run(f.env);
    assert.notEqual(result.status, 0);
    assert.equal(check(result.report, 'tool_versions').ok, false);
  });
});

test('an occupied auth lock fails readiness', (t) => {
  const f = fixture(t);
  executable(f.flock, 'exit 1');
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'auth_lock').available, false);
});

test('an unavailable Chromium probe fails readiness', (t) => {
  const f = fixture(t);
  executable(f.browser, 'exit 1');
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'browser').available, false);
});

test('rejects a non-private repository and a conflicting runner list', (t) => {
  const f = fixture(t);
  executable(f.env.QA_GH_BIN, `
if [[ "$1" == 'repo' ]]; then echo '{"nameWithOwner":"jayn2u/gods-eye","isPrivate":false}'; else echo '{"runners":[{"name":"gods-eye-agent-qa","labels":[]},{"name":"gods-eye-agent-qa","labels":[]}]}'; fi`);
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'repository').private, false);
  assert.equal(check(result.report, 'runner_registration').exact_count, 2);
});

test('start phase permits an inactive service but no other failed prerequisite', (t) => {
  const f = fixture(t);
  executable(f.env.QA_SYSTEMCTL_BIN, 'exit 3');
  const start = run(f.env, ['--phase', 'start']);
  assert.equal(start.status, 0);
  assert.equal(start.report.ok, true);
  assert.equal(check(start.report, 'runner_service').ok, false);
  const status = run(f.env);
  assert.notEqual(status.status, 0);
  assert.equal(status.report.ok, false);
});

test('a version-looking error cannot masquerade as a successful tool probe', (t) => {
  const f = fixture(t);
  executable(f.env.QA_PLAYWRIGHT_MCP_BIN, "echo 'Version 0.0.80'; exit 1");
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'tool_versions').playwright_mcp, '0.0.80');
  assert.equal(check(result.report, 'tool_versions').ok, false);
});

test('malformed CLI arguments emit no preflight JSON', () => {
  const result = spawnSync(process.execPath, [doctor, '--json', '--phase', 'start', 'extra'], { encoding: 'utf8' });
  assert.equal(result.status, 2);
  assert.equal(result.stdout, '');
  assert.match(result.stderr, /Usage:/);
});
