'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const projectRoot = path.resolve(__dirname, '../../..');
const doctor = path.join(projectRoot, '.github/agent-qa/doctor.cjs');
const SECRET = 'DOCTOR_SECRET_CANARY_4f2095';

function executable(target, body) {
  fs.writeFileSync(target, `#!/usr/bin/env bash\nset -euo pipefail\n${body}\n`, { mode: 0o700 });
}

function fixture(t) {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-qa-doctor-'));
  t.after(() => {
    fs.rmSync(temp, { recursive: true, force: true });
    assert.equal(fs.existsSync(temp), false);
  });
  const qaRoot = path.join(temp, 'qa-root');
  const runner = path.join(qaRoot, 'runner');
  const toolchain = path.join(qaRoot, 'toolchain');
  const codexHome = path.join(qaRoot, 'codex-home');
  for (const dir of [qaRoot, runner, toolchain, codexHome, path.join(qaRoot, 'runs')]) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
    fs.chmodSync(dir, 0o700);
  }
  executable(path.join(runner, 'run.sh'), 'exit 0');
  fs.writeFileSync(path.join(runner, '.runner-version'), '2.337.0\n');
  fs.writeFileSync(path.join(runner, '.runner'),
    '{"agentName":"gods-eye-agent-qa","gitHubUrl":"https://github.com/jayn2u/gods-eye"}');
  const auth = path.join(codexHome, 'auth.json');
  fs.writeFileSync(auth, JSON.stringify({ auth_mode: 'chatgpt', tokens: { access_token: SECRET } }), { mode: 0o600 });
  fs.chmodSync(auth, 0o600);
  fs.writeFileSync(path.join(qaRoot, 'auth.lock'), '', { mode: 0o600 });

  const codex = path.join(temp, 'codex');
  executable(codex, `
if [[ "\${1:-}" == '--version' ]]; then echo 'codex-cli 0.153.3'; exit; fi
if [[ "\${1:-}" == 'login' && "\${2:-}" == 'status' ]]; then echo 'Logged in using ChatGPT'; exit; fi
exit 1`);
  const uv = path.join(temp, 'uv');
  executable(uv, "echo 'uv 0.12.6'");
  const mcp = path.join(temp, 'playwright-mcp');
  executable(mcp, "echo 'Version 0.0.80'");
  const pnpm = path.join(temp, 'pnpm');
  executable(pnpm, "echo '10.15.0'");
  const browser = path.join(temp, 'browser-probe');
  executable(browser, 'exit 0');
  const gh = path.join(temp, 'gh');
  executable(gh, `
if [[ "$1" == 'repo' ]]; then echo '{"nameWithOwner":"jayn2u/gods-eye","isPrivate":true}'; else echo '{"runners":[{"name":"gods-eye-agent-qa","labels":[{"name":"gods-eye-agent-qa"}]}]}'; fi`);
  const systemctl = path.join(temp, 'systemctl');
  executable(systemctl, "echo active");
  const loginctl = path.join(temp, 'loginctl');
  executable(loginctl, "echo yes");
  const flock = path.join(temp, 'flock');
  executable(flock, 'exit 0');

  const env = {
    ...process.env,
    QA_ROOT: qaRoot,
    QA_DEVELOPER_CHECKOUT: projectRoot,
    QA_CODEX_BIN: codex,
    QA_UV_BIN: uv,
    QA_PLAYWRIGHT_MCP_BIN: mcp,
    QA_PNPM_BIN: pnpm,
    QA_BROWSER_PROBE_BIN: browser,
    QA_GH_BIN: gh,
    QA_SYSTEMCTL_BIN: systemctl,
    QA_LOGINCTL_BIN: loginctl,
    QA_FLOCK_BIN: flock,
  };
  delete env.OPENAI_API_KEY;
  delete env.AZURE_OPENAI_API_KEY;
  delete env.CODEX_API_KEY;
  return { temp, qaRoot, codexHome, auth, browser, flock, env };
}

function run(env, extraArgs = []) {
  const result = spawnSync(process.execPath, [doctor, '--json', ...extraArgs], { env, encoding: 'utf8' });
  assert.doesNotThrow(() => JSON.parse(result.stdout), `stdout was not JSON: ${result.stdout}`);
  return { ...result, report: JSON.parse(result.stdout) };
}

function check(report, name) {
  return report.checks.find((item) => item.name === name);
}

test('reports ready from validated ChatGPT auth and non-secret metadata', (t) => {
  const f = fixture(t);
  const result = run(f.env);
  assert.equal(result.status, 0);
  assert.equal(result.report.ok, true);
  assert.ok(result.report.checks.every((item) => item.ok));
  assert.equal(check(result.report, 'subscription_auth').mode, 'chatgpt');
  assert.doesNotMatch(`${result.stdout}${result.stderr}`, new RegExp(SECRET));
  assert.doesNotMatch(result.stdout, /access_token|refresh_token|id_token/);
});

test('recognizes a BOM-prefixed runner configuration generated by the real runner', (t) => {
  const f = fixture(t);
  fs.writeFileSync(path.join(f.qaRoot, 'runner/.runner'), Buffer.concat([
    Buffer.from([0xef, 0xbb, 0xbf]),
    Buffer.from('{"agentName":"gods-eye-agent-qa","gitHubUrl":"https://github.com/jayn2u/gods-eye"}'),
  ]));
  const result = run(f.env);
  assert.equal(result.status, 0);
  assert.equal(check(result.report, 'runner_registration').local_configured, true);
});

test('auth file presence without successful login status is not accepted', (t) => {
  const f = fixture(t);
  executable(f.env.QA_CODEX_BIN, `if [[ "\${1:-}" == '--version' ]]; then echo 'codex-cli 0.153.3'; exit; fi; exit 1`);
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'subscription_auth').auth_file_present, true);
  assert.equal(check(result.report, 'subscription_auth').login_status_verified, false);
  assert.equal(check(result.report, 'subscription_auth').ok, false);
});

test('rejects API-key environment even when ChatGPT status is valid', (t) => {
  const f = fixture(t);
  const result = run({ ...f.env, OPENAI_API_KEY: SECRET });
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'subscription_auth').api_environment_present, true);
  assert.equal(check(result.report, 'subscription_auth').ok, false);
  assert.doesNotMatch(`${result.stdout}${result.stderr}`, new RegExp(SECRET));
});

test('an occupied auth lock fails readiness', (t) => {
  const f = fixture(t);
  executable(f.flock, 'exit 1');
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'auth_lock').available, false);
});

test('an unavailable Chromium probe fails readiness', (t) => {
  const f = fixture(t);
  executable(f.browser, 'exit 1');
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'browser').available, false);
});

test('rejects a non-private repository and a conflicting runner list', (t) => {
  const f = fixture(t);
  executable(f.env.QA_GH_BIN, `
if [[ "$1" == 'repo' ]]; then echo '{"nameWithOwner":"jayn2u/gods-eye","isPrivate":false}'; else echo '{"runners":[{"name":"gods-eye-agent-qa","labels":[]},{"name":"gods-eye-agent-qa","labels":[]}]}'; fi`);
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'repository').private, false);
  assert.equal(check(result.report, 'runner_registration').exact_count, 2);
});

test('start phase permits an inactive service but no other failed prerequisite', (t) => {
  const f = fixture(t);
  executable(f.env.QA_SYSTEMCTL_BIN, 'exit 3');
  const start = run(f.env, ['--phase', 'start']);
  assert.equal(start.status, 0);
  assert.equal(start.report.ok, true);
  assert.equal(check(start.report, 'runner_service').ok, false);
  const status = run(f.env);
  assert.notEqual(status.status, 0);
  assert.equal(status.report.ok, false);
});

test('a version-looking error cannot masquerade as a successful tool probe', (t) => {
  const f = fixture(t);
  executable(f.env.QA_PLAYWRIGHT_MCP_BIN, "echo 'Version 0.0.80'; exit 1");
  const result = run(f.env);
  assert.notEqual(result.status, 0);
  assert.equal(check(result.report, 'tool_versions').playwright_mcp, '0.0.80');
  assert.equal(check(result.report, 'tool_versions').ok, false);
});

test('malformed CLI arguments emit no preflight JSON', () => {
  const result = spawnSync(process.execPath, [doctor, '--json', '--phase', 'start', 'extra'], { encoding: 'utf8' });
  assert.equal(result.status, 2);
  assert.equal(result.stdout, '');
  assert.match(result.stderr, /Usage:/);
});
