import React from 'react'
import { GALLERIES, type SearchResult } from './types'

export function ComposeScreen(props: { query: string; datasets: string[]; topK: number; ready: boolean | null; guidance: string; error: string; onQuery: (value: string) => void; onToggle: (dataset: string) => void; onTopK: (value: number) => void; onSubmit: (event?: React.FormEvent) => void; onReadiness: () => void }) {
  return <section className="panel compose" aria-labelledby="compose-title"><p className="section-number">01 / COMPOSE</p><h2 id="compose-title">Who are you looking for?</h2><p className="lede">Describe clothing, colors, accessories, and other visible attributes in English.</p><form onSubmit={props.onSubmit} noValidate>
    <label htmlFor="query">Person description</label><textarea autoFocus id="query" value={props.query} onChange={event => props.onQuery(event.target.value)} aria-describedby="query-help error" placeholder="A person wearing a pale blue coat and carrying a black shoulder bag…"/><small id="query-help">Do not enter names, camera locations, or time ranges.</small>
    <div className="controls"><fieldset><legend>Search galleries</legend><div className="checks">{GALLERIES.map(dataset => <label className="check" key={dataset}><input type="checkbox" checked={props.datasets.includes(dataset)} onChange={() => props.onToggle(dataset)}/><span>{dataset}</span></label>)}</div></fieldset><label className="select-label" htmlFor="top-k">Maximum results<select id="top-k" value={props.topK} onChange={event => props.onTopK(Number(event.target.value))}><option>12</option><option>24</option><option>48</option></select></label></div>
    {props.ready === false && <aside className="notice" role="status"><strong>Search index unavailable</strong><p>{props.guidance}</p><button type="button" className="text-button" onClick={props.onReadiness}>Check again</button></aside>}
    {props.error && <aside id="error" className="notice" role="alert"><strong>Search interrupted</strong><p>{props.error}</p><button type="button" className="text-button" onClick={() => props.onSubmit()}>Retry search</button></aside>}
    <button className="primary" disabled={props.ready !== true}>Search gallery <span aria-hidden>→</span></button>
  </form></section>
}

export function ProgressScreen({ query, onCancel }: { query: string; onCancel: () => void }) {
  return <section className="panel progress-panel" aria-live="polite" aria-labelledby="progress-title"><p className="section-number">02 / SEARCH PROGRESS</p><h2 id="progress-title">Search request in progress</h2><p className="query-quote">“{query}”</p><div className="scanner" aria-hidden><span/></div><p>The service is encoding the query and searching the active index. Results appear when that HTTP request completes.</p><button className="secondary" onClick={onCancel}>Cancel search</button></section>
}

export function ResultsScreen(props: { query: string; results: SearchResult[]; visible: number; onRefine: () => void; onSelect: (index: number) => void; onMore: () => void }) {
  return <section className="results" aria-labelledby="results-title"><div className="results-heading"><div><p className="section-number">03 / RESULTS</p><h2 id="results-title">Closest visual matches</h2><p>Showing {Math.min(props.visible, props.results.length)} of {props.results.length} results for “{props.query}”</p></div><button className="secondary" onClick={props.onRefine}>Refine search</button></div><p className="score-note"><strong>About similarity:</strong> Visual-text closeness, not an identity probability.</p>
    {!props.results.length ? <div className="empty"><h3>No matches returned</h3><p>Try a broader description or another gallery.</p><button className="primary" onClick={props.onRefine}>Revise description</button></div> : <><div className="grid" aria-live="polite">{props.results.slice(0, props.visible).map((result, index) => <article className="card" key={result.id}><button data-card={index} onClick={() => props.onSelect(index)} aria-label={`Open result ${result.rank} from ${result.dataset}`}><img src={result.image_url} alt={`Gallery result ranked ${result.rank}`} loading="lazy"/><div><strong>#{result.rank}</strong><span>Similarity {result.similarity.toFixed(3)}</span></div><p>{result.dataset} · {result.split}</p><code>{result.id}</code></button></article>)}</div>{props.visible < props.results.length && <button className="load-more" onClick={props.onMore}>Load 24 more</button>}</>}
  </section>
}

export function DetailScreen(props: { detail: SearchResult; selectedIndex: number; total: number; backRef: React.RefObject<HTMLButtonElement | null>; onClose: () => void; onMove: (next: number) => void }) {
  const { detail, selectedIndex } = props
  return <section className="panel detail" aria-labelledby="detail-title" onKeyDown={event => { if (event.key === 'Escape') props.onClose(); if (event.key === 'ArrowLeft' && selectedIndex > 0) props.onMove(selectedIndex - 1); if (event.key === 'ArrowRight' && selectedIndex < props.total - 1) props.onMove(selectedIndex + 1) }}><div className="detail-head"><div><p className="section-number">04 / IMAGE DETAIL</p><h2 id="detail-title">Result #{detail.rank}</h2></div><button ref={props.backRef} className="secondary" onClick={props.onClose}>Back to results</button></div><div className="detail-body"><img src={detail.image_url} alt={`Expanded gallery result ranked ${detail.rank}`}/><dl><div><dt>Similarity</dt><dd>{detail.similarity.toFixed(4)}</dd></div><div><dt>Dataset</dt><dd>{detail.dataset}</dd></div><div><dt>Split</dt><dd>{detail.split}</dd></div><div><dt>Image ID</dt><dd><code>{detail.id}</code></dd></div></dl></div><div className="detail-nav"><button className="secondary" disabled={selectedIndex === 0} onClick={() => props.onMove(selectedIndex - 1)}>← Previous</button><span>{selectedIndex + 1} / {props.total}</span><button className="secondary" disabled={selectedIndex === props.total - 1} onClick={() => props.onMove(selectedIndex + 1)}>Next →</button></div></section>
}
